import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });

import { createClient } from "@supabase/supabase-js";
import { computeJobContentHash } from "../lib/ingestion/hasher";
import { NormalizedJob } from "../lib/ingestion/types";

const WELLFOUND_SAMPLE_JOBS: NormalizedJob[] = [
  {
    source: "wellfound",
    source_job_id: "wf-replit-1",
    company_name: "Replit",
    company_logo: "/platforms/wellfound.png",
    title: "Senior AI Systems Engineer",
    description: "Build scalable infrastructure for AI code generation models, workspace agents, and interactive coding assistants powering millions of developers.",
    description_html: "<p>Build scalable infrastructure for AI code generation models, workspace agents, and interactive coding assistants powering millions of developers.</p>",
    location: "San Francisco, CA / Remote",
    locations_json: ["San Francisco, CA", "Remote"],
    country: "United States",
    region: "California",
    city: "San Francisco",
    remote_type: "hybrid",
    employment_type: "full-time",
    department: "AI Research",
    team: "Model Inference",
    salary_min: 190000,
    salary_max: 270000,
    salary_currency: "USD",
    salary_interval: "yearly",
    job_url: "https://wellfound.com/company/replit/jobs/senior-ai-systems-engineer",
    apply_url: "https://wellfound.com/company/replit/jobs/senior-ai-systems-engineer/apply",
    posted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at_source: new Date().toISOString(),
    raw_payload: {},
  },
  {
    source: "wellfound",
    source_job_id: "wf-anysphere-1",
    company_name: "Anysphere (Cursor)",
    company_logo: "/platforms/wellfound.png",
    title: "Staff Full Stack Engineer - AI IDE",
    description: "Join the Cursor core engineering team building the next generation AI editor. Work on editor extensions, model fine-tuning, and semantic indexing at scale.",
    description_html: "<p>Join the Cursor core engineering team building the next generation AI editor. Work on editor extensions, model fine-tuning, and semantic indexing at scale.</p>",
    location: "San Francisco, CA",
    locations_json: ["San Francisco, CA"],
    country: "United States",
    region: "California",
    city: "San Francisco",
    remote_type: "onsite",
    employment_type: "full-time",
    department: "Core Engineering",
    team: "IDE Architecture",
    salary_min: 220000,
    salary_max: 320000,
    salary_currency: "USD",
    salary_interval: "yearly",
    job_url: "https://wellfound.com/company/anysphere/jobs/staff-full-stack-engineer",
    apply_url: "https://wellfound.com/company/anysphere/jobs/staff-full-stack-engineer/apply",
    posted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at_source: new Date().toISOString(),
    raw_payload: {},
  },
  {
    source: "wellfound",
    source_job_id: "wf-resend-1",
    company_name: "Resend",
    company_logo: "/platforms/wellfound.png",
    title: "Senior Developer Experience (DX) Engineer",
    description: "Design developer tools, SDKs, and intuitive APIs for modern transactional email infrastructure. TypeScript, React, Next.js, and distributed mail processing.",
    description_html: "<p>Design developer tools, SDKs, and intuitive APIs for modern transactional email infrastructure. TypeScript, React, Next.js, and distributed mail processing.</p>",
    location: "Remote",
    locations_json: ["Remote"],
    country: "United States",
    region: null,
    city: null,
    remote_type: "remote",
    employment_type: "full-time",
    department: "Developer Experience",
    team: "Platform DX",
    salary_min: 160000,
    salary_max: 220000,
    salary_currency: "USD",
    salary_interval: "yearly",
    job_url: "https://wellfound.com/company/resend/jobs/senior-dx-engineer",
    apply_url: "https://wellfound.com/company/resend/jobs/senior-dx-engineer/apply",
    posted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at_source: new Date().toISOString(),
    raw_payload: {},
  },
  {
    source: "wellfound",
    source_job_id: "wf-langchain-1",
    company_name: "LangChain",
    company_logo: "/platforms/wellfound.png",
    title: "Founding Distributed Systems Architect",
    description: "Build LangSmith and high-throughput evaluation & observability primitives for LLM applications. Rust, Python, ClickHouse, and Kubernetes.",
    description_html: "<p>Build LangSmith and high-throughput evaluation & observability primitives for LLM applications. Rust, Python, ClickHouse, and Kubernetes.</p>",
    location: "San Francisco, CA / Remote",
    locations_json: ["San Francisco, CA", "Remote"],
    country: "United States",
    region: "California",
    city: "San Francisco",
    remote_type: "hybrid",
    employment_type: "full-time",
    department: "Infrastructure",
    team: "LangSmith Engine",
    salary_min: 200000,
    salary_max: 290000,
    salary_currency: "USD",
    salary_interval: "yearly",
    job_url: "https://wellfound.com/company/langchain/jobs/founding-systems-architect",
    apply_url: "https://wellfound.com/company/langchain/jobs/founding-systems-architect/apply",
    posted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at_source: new Date().toISOString(),
    raw_payload: {},
  },
  {
    source: "wellfound",
    source_job_id: "wf-elevenlabs-1",
    company_name: "ElevenLabs",
    company_logo: "/platforms/wellfound.png",
    title: "Audio AI Research & Pipeline Engineer",
    description: "Develop cutting-edge generative audio models, low-latency streaming speech synthesis, and real-time voice cloning engines.",
    description_html: "<p>Develop cutting-edge generative audio models, low-latency streaming speech synthesis, and real-time voice cloning engines.</p>",
    location: "New York, NY / Remote",
    locations_json: ["New York, NY", "Remote"],
    country: "United States",
    region: "New York",
    city: "New York",
    remote_type: "remote",
    employment_type: "full-time",
    department: "Research",
    team: "Voice Generation",
    salary_min: 210000,
    salary_max: 300000,
    salary_currency: "USD",
    salary_interval: "yearly",
    job_url: "https://wellfound.com/company/elevenlabs/jobs/audio-ai-pipeline-engineer",
    apply_url: "https://wellfound.com/company/elevenlabs/jobs/audio-ai-pipeline-engineer/apply",
    posted_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at_source: new Date().toISOString(),
    raw_payload: {},
  },
  {
    source: "wellfound",
    source_job_id: "wf-supabase-1",
    company_name: "Supabase",
    company_logo: "/platforms/wellfound.png",
    title: "Senior Backend Engineer - Database Infrastructure",
    description: "Scale open source PostgreSQL hosting, connection poolers, Auth, Realtime, and Storage across global cloud regions. Go, Rust, Elixir, and PostgreSQL.",
    description_html: "<p>Scale open source PostgreSQL hosting, connection poolers, Auth, Realtime, and Storage across global cloud regions. Go, Rust, Elixir, and PostgreSQL.</p>",
    location: "Remote Worldwide",
    locations_json: ["Remote Worldwide"],
    country: null,
    region: null,
    city: null,
    remote_type: "remote",
    employment_type: "full-time",
    department: "Database Platform",
    team: "Core Storage",
    salary_min: 175000,
    salary_max: 250000,
    salary_currency: "USD",
    salary_interval: "yearly",
    job_url: "https://wellfound.com/company/supabase/jobs/senior-backend-infra",
    apply_url: "https://wellfound.com/company/supabase/jobs/senior-backend-infra/apply",
    posted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at_source: new Date().toISOString(),
    raw_payload: {},
  },
  {
    source: "wellfound",
    source_job_id: "wf-modal-2",
    company_name: "Modal Labs",
    company_logo: "/platforms/wellfound.png",
    title: "Senior Cloud Security Engineer",
    description: "Lead cloud infrastructure security, zero-trust container isolation, and kernel sandbox defenses for massive parallel computation workloads.",
    description_html: "<p>Lead cloud infrastructure security, zero-trust container isolation, and kernel sandbox defenses for massive parallel computation workloads.</p>",
    location: "San Francisco, CA / New York, NY",
    locations_json: ["San Francisco, CA", "New York, NY"],
    country: "United States",
    region: "California",
    city: "San Francisco",
    remote_type: "onsite",
    employment_type: "full-time",
    department: "Security",
    team: "Platform Security",
    salary_min: 210000,
    salary_max: 290000,
    salary_currency: "USD",
    salary_interval: "yearly",
    job_url: "https://wellfound.com/company/modal-labs/jobs/senior-security-engineer",
    apply_url: "https://wellfound.com/company/modal-labs/jobs/senior-security-engineer/apply",
    posted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at_source: new Date().toISOString(),
    raw_payload: {},
  },
  {
    source: "wellfound",
    source_job_id: "wf-linear-1",
    company_name: "Linear",
    company_logo: "/platforms/wellfound.png",
    title: "Product Engineer - Desktop & Sync Engine",
    description: "Craft pixel-perfect, high-performance issue tracking interfaces, local-first SQLite sync architectures, and real-time multiplayer state management.",
    description_html: "<p>Craft pixel-perfect, high-performance issue tracking interfaces, local-first SQLite sync architectures, and real-time multiplayer state management.</p>",
    location: "San Francisco, CA / Remote",
    locations_json: ["San Francisco, CA", "Remote"],
    country: "United States",
    region: "California",
    city: "San Francisco",
    remote_type: "hybrid",
    employment_type: "full-time",
    department: "Product Engineering",
    team: "Core Desktop",
    salary_min: 190000,
    salary_max: 260000,
    salary_currency: "USD",
    salary_interval: "yearly",
    job_url: "https://wellfound.com/company/linear/jobs/product-engineer-sync",
    apply_url: "https://wellfound.com/company/linear/jobs/product-engineer-sync/apply",
    posted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at_source: new Date().toISOString(),
    raw_payload: {},
  }
];

async function seedWellfound() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://aeqkkdnjzoimgdfmypcw.supabase.co";
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
    "";

  const supabase = createClient(url, key);
  const nowIso = new Date().toISOString();

  console.log(`\n🌱 Seeding ${WELLFOUND_SAMPLE_JOBS.length} Wellfound canonical jobs into Supabase...\n`);

  const payloads = WELLFOUND_SAMPLE_JOBS.map((j) => ({
    source: "wellfound",
    source_job_id: j.source_job_id,
    company_name: j.company_name,
    company_logo: j.company_logo,
    title: j.title,
    description: j.description,
    description_html: j.description_html,
    location: j.location,
    locations_json: j.locations_json,
    country: j.country,
    region: j.region,
    city: j.city,
    remote_type: j.remote_type,
    employment_type: j.employment_type,
    department: j.department,
    team: j.team,
    salary_min: j.salary_min,
    salary_max: j.salary_max,
    salary_currency: j.salary_currency,
    salary_interval: j.salary_interval,
    job_url: j.job_url,
    apply_url: j.apply_url,
    posted_at: j.posted_at,
    updated_at_source: j.updated_at_source,
    scraped_at: nowIso,
    last_seen_at: nowIso,
    active: true,
    raw_payload: j.raw_payload,
    content_hash: computeJobContentHash(j),
    updated_at: nowIso,
  }));

  const { data, error } = await supabase
    .from("canonical_jobs")
    .upsert(payloads, { onConflict: "source,source_job_id" })
    .select("id, source, title, company_name");

  if (error) {
    console.error("Error upserting Wellfound jobs:", error);
    process.exit(1);
  }

  console.log(`✅ Successfully seeded ${data?.length || payloads.length} Wellfound canonical jobs!\n`);
}

seedWellfound().catch(console.error);
