import { DiscoveredSource } from "./types";

export const INITIAL_JOB_SOURCES: DiscoveredSource[] = [
  // --- Greenhouse Sources ---
  {
    source: "greenhouse",
    source_name: "Stripe",
    source_identifier: "stripe",
    company_name: "Stripe",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/stripe",
  },
  {
    source: "greenhouse",
    source_name: "Figma",
    source_identifier: "figma",
    company_name: "Figma",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/figma",
  },
  {
    source: "greenhouse",
    source_name: "Scale AI",
    source_identifier: "scaleai",
    company_name: "Scale AI",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/scaleai",
  },
  {
    source: "greenhouse",
    source_name: "Airbnb",
    source_identifier: "airbnb",
    company_name: "Airbnb",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/airbnb",
  },
  {
    source: "greenhouse",
    source_name: "Datadog",
    source_identifier: "datadog",
    company_name: "Datadog",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/datadog",
  },
  {
    source: "greenhouse",
    source_name: "Cloudflare",
    source_identifier: "cloudflare",
    company_name: "Cloudflare",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/cloudflare",
  },
  {
    source: "greenhouse",
    source_name: "Discord",
    source_identifier: "discord",
    company_name: "Discord",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/discord",
  },
  {
    source: "greenhouse",
    source_name: "Brex",
    source_identifier: "brex",
    company_name: "Brex",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/brex",
  },
  {
    source: "greenhouse",
    source_name: "Anthropic",
    source_identifier: "anthropic",
    company_name: "Anthropic",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/anthropic",
  },
  {
    source: "greenhouse",
    source_name: "Vercel",
    source_identifier: "vercel",
    company_name: "Vercel",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/vercel",
  },
  {
    source: "greenhouse",
    source_name: "Postman",
    source_identifier: "postman",
    company_name: "Postman",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/postman",
  },
  {
    source: "greenhouse",
    source_name: "Coinbase",
    source_identifier: "coinbase",
    company_name: "Coinbase",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/coinbase",
  },
  {
    source: "greenhouse",
    source_name: "Reddit",
    source_identifier: "reddit",
    company_name: "Reddit",
    company_logo: "/platforms/Greenhouse.png",
    source_url: "https://boards.greenhouse.io/reddit",
  },

  // --- Lever Sources ---
  {
    source: "lever",
    source_name: "Outreach",
    source_identifier: "outreach",
    company_name: "Outreach",
    company_logo: "/platforms/Lever.png",
    source_url: "https://jobs.lever.co/outreach",
  },
  {
    source: "lever",
    source_name: "Spotify",
    source_identifier: "spotify",
    company_name: "Spotify",
    company_logo: "/platforms/Lever.png",
    source_url: "https://jobs.lever.co/spotify",
  },
  {
    source: "lever",
    source_name: "Palantir",
    source_identifier: "palantir",
    company_name: "Palantir",
    company_logo: "/platforms/Lever.png",
    source_url: "https://jobs.lever.co/palantir",
  },
  {
    source: "lever",
    source_name: "Wealthfront",
    source_identifier: "wealthfront",
    company_name: "Wealthfront",
    company_logo: "/platforms/Lever.png",
    source_url: "https://jobs.lever.co/wealthfront",
  },

  // --- Ashby Sources ---
  {
    source: "ashby",
    source_name: "OpenAI",
    source_identifier: "openai",
    company_name: "OpenAI",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/openai",
  },
  {
    source: "ashby",
    source_name: "Linear",
    source_identifier: "linear",
    company_name: "Linear",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/linear",
  },
  {
    source: "ashby",
    source_name: "Cursor",
    source_identifier: "cursor",
    company_name: "Cursor",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/cursor",
  },
  {
    source: "ashby",
    source_name: "Ramp",
    source_identifier: "ramp",
    company_name: "Ramp",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/ramp",
  },
  {
    source: "ashby",
    source_name: "PostHog",
    source_identifier: "posthog",
    company_name: "PostHog",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/posthog",
  },
  {
    source: "ashby",
    source_name: "Supabase",
    source_identifier: "supabase",
    company_name: "Supabase",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/supabase",
  },
  {
    source: "ashby",
    source_name: "Perplexity AI",
    source_identifier: "perplexity",
    company_name: "Perplexity AI",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/perplexity",
  },
  {
    source: "ashby",
    source_name: "Synthesia",
    source_identifier: "synthesia",
    company_name: "Synthesia",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/synthesia",
  },
  {
    source: "ashby",
    source_name: "Replit",
    source_identifier: "replit",
    company_name: "Replit",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/replit",
  },
  {
    source: "ashby",
    source_name: "Cohere",
    source_identifier: "cohere",
    company_name: "Cohere",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/cohere",
  },
  {
    source: "ashby",
    source_name: "Modal",
    source_identifier: "modal",
    company_name: "Modal",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/modal",
  },
  {
    source: "ashby",
    source_name: "Sentry",
    source_identifier: "sentry",
    company_name: "Sentry",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/sentry",
  },
  {
    source: "ashby",
    source_name: "Resend",
    source_identifier: "resend",
    company_name: "Resend",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/resend",
  },
  {
    source: "ashby",
    source_name: "Vapi",
    source_identifier: "vapi",
    company_name: "Vapi",
    company_logo: "/platforms/Ashby.png",
    source_url: "https://jobs.ashbyhq.com/vapi",
  },

  // --- Workable Sources ---
  {
    source: "workable",
    source_name: "Starling Bank",
    source_identifier: "starling-bank",
    company_name: "Starling Bank",
    company_logo: "/platforms/Workable.png",
    source_url: "https://apply.workable.com/starling-bank",
  },
  {
    source: "workable",
    source_name: "Treatwell",
    source_identifier: "treatwell",
    company_name: "Treatwell",
    company_logo: "/platforms/Workable.png",
    source_url: "https://apply.workable.com/treatwell",
  },
  {
    source: "workable",
    source_name: "Zoopla",
    source_identifier: "zoopla",
    company_name: "Zoopla",
    company_logo: "/platforms/Workable.png",
    source_url: "https://apply.workable.com/zoopla",
  },

  // --- Wellfound Sources ---
  {
    source: "wellfound",
    source_name: "Modal Labs",
    source_identifier: "modal-labs",
    company_name: "Modal Labs",
    company_logo: "/platforms/wellfound.png",
    source_url: "https://wellfound.com/company/modal-labs",
  },
  {
    source: "wellfound",
    source_name: "Replit",
    source_identifier: "replit",
    company_name: "Replit",
    company_logo: "/platforms/wellfound.png",
    source_url: "https://wellfound.com/company/replit",
  },
  {
    source: "wellfound",
    source_name: "Anysphere (Cursor)",
    source_identifier: "anysphere",
    company_name: "Anysphere (Cursor)",
    company_logo: "/platforms/wellfound.png",
    source_url: "https://wellfound.com/company/anysphere",
  },
  {
    source: "wellfound",
    source_name: "Resend",
    source_identifier: "resend",
    company_name: "Resend",
    company_logo: "/platforms/wellfound.png",
    source_url: "https://wellfound.com/company/resend",
  },

  // --- SmartRecruiters Sources ---
  {
    source: "smartrecruiters",
    source_name: "SmartRecruiters",
    source_identifier: "SmartRecruiters",
    company_name: "SmartRecruiters Inc",
    company_logo: "/platforms/SmartRecruiters.png",
    source_url: "https://jobs.smartrecruiters.com/SmartRecruiters",
  },
  {
    source: "smartrecruiters",
    source_name: "Avery Dennison",
    source_identifier: "AveryDennison",
    company_name: "Avery Dennison",
    company_logo: "/platforms/SmartRecruiters.png",
    source_url: "https://jobs.smartrecruiters.com/AveryDennison",
  },
  {
    source: "smartrecruiters",
    source_name: "CERN",
    source_identifier: "CERN",
    company_name: "CERN",
    company_logo: "/platforms/SmartRecruiters.png",
    source_url: "https://jobs.smartrecruiters.com/CERN",
  },
  {
    source: "smartrecruiters",
    source_name: "Ubisoft",
    source_identifier: "Ubisoft2",
    company_name: "Ubisoft",
    company_logo: "/platforms/SmartRecruiters.png",
    source_url: "https://jobs.smartrecruiters.com/Ubisoft2",
  },
  // --- Y Combinator Sources ---
  {
    source: "ycombinator",
    source_name: "Y Combinator Job Directory",
    source_identifier: "ycombinator-jobs",
    company_name: "Y Combinator",
    company_logo: "/platforms/ycombinator.png",
    source_url: "https://www.ycombinator.com/jobs",
  },
  // --- Adzuna Sources ---
  {
    source: "adzuna",
    source_name: "Adzuna India Tech Jobs",
    source_identifier: "software engineer",
    company_name: "Adzuna (India)",
    company_logo: "/platforms/adzuna.svg",
    source_url: "https://www.adzuna.in",
    metadata: {
      country: "in",
      location: "India",
      resultsPerPage: 30,
    },
  },
  {
    source: "adzuna",
    source_name: "Adzuna Global Tech Jobs",
    source_identifier: "developer",
    company_name: "Adzuna (Global)",
    company_logo: "/platforms/adzuna.svg",
    source_url: "https://www.adzuna.com",
    metadata: {
      country: "gb",
      resultsPerPage: 30,
    },
  },
];

